// ─── Dashboard Stats ────────────────────────────────────────────────────────
export const MOCK_DASHBOARD_STATS = {
  totalUsers: 14_820,
  totalSellers: 342,
  totalProducts: 8_961,
  totalOrders: 23_540,
  totalRevenue: 1_284_390,
  pendingApplications: 17,
  revenueGrowth: 12.4,
  ordersGrowth: 8.7,
  usersGrowth: 5.2,
  sellersGrowth: 3.1,
};

// ─── Revenue Chart (Monthly) ─────────────────────────────────────────────────
export const MOCK_REVENUE_DATA = [
  { month: "Jan", revenue: 65000, orders: 1200 },
  { month: "Feb", revenue: 78000, orders: 1450 },
  { month: "Mar", revenue: 90000, orders: 1700 },
  { month: "Apr", revenue: 81000, orders: 1560 },
  { month: "May", revenue: 95000, orders: 1820 },
  { month: "Jun", revenue: 110000, orders: 2100 },
  { month: "Jul", revenue: 102000, orders: 1950 },
  { month: "Aug", revenue: 118000, orders: 2250 },
  { month: "Sep", revenue: 125000, orders: 2380 },
  { month: "Oct", revenue: 138000, orders: 2600 },
  { month: "Nov", revenue: 155000, orders: 2900 },
  { month: "Dec", revenue: 172000, orders: 3200 },
];

// ─── Category Distribution ───────────────────────────────────────────────────
export const MOCK_CATEGORY_DATA = [
  { name: "Electronics", value: 35, color: "#3b82f6" },
  { name: "Fashion", value: 25, color: "#8b5cf6" },
  { name: "Home & Garden", value: 15, color: "#10b981" },
  { name: "Sports", value: 12, color: "#f59e0b" },
  { name: "Books", value: 8, color: "#ef4444" },
  { name: "Other", value: 5, color: "#6b7280" },
];

// ─── Recent Orders ───────────────────────────────────────────────────────────
export const MOCK_RECENT_ORDERS = [
  {
    id: "ORD-7821",
    customer: "Alice Johnson",
    avatar: null,
    seller: "TechZone",
    amount: 249.99,
    status: "delivered",
    payment: "paid",
    date: "2024-12-15",
    items: 3,
  },
  {
    id: "ORD-7820",
    customer: "Bob Martinez",
    avatar: null,
    seller: "FashionHub",
    amount: 89.5,
    status: "processing",
    payment: "paid",
    date: "2024-12-15",
    items: 1,
  },
  {
    id: "ORD-7819",
    customer: "Carol White",
    avatar: null,
    seller: "HomeDecor",
    amount: 399.0,
    status: "shipped",
    payment: "paid",
    date: "2024-12-14",
    items: 2,
  },
  {
    id: "ORD-7818",
    customer: "David Kim",
    avatar: null,
    seller: "SportsPro",
    amount: 125.75,
    status: "pending",
    payment: "pending",
    date: "2024-12-14",
    items: 4,
  },
  {
    id: "ORD-7817",
    customer: "Emma Davis",
    avatar: null,
    seller: "BookWorld",
    amount: 45.0,
    status: "cancelled",
    payment: "refunded",
    date: "2024-12-13",
    items: 2,
  },
  {
    id: "ORD-7816",
    customer: "Frank Lee",
    avatar: null,
    seller: "TechZone",
    amount: 599.99,
    status: "delivered",
    payment: "paid",
    date: "2024-12-13",
    items: 1,
  },
];

// ─── Top Products ────────────────────────────────────────────────────────────
export const MOCK_TOP_PRODUCTS = [
  {
    id: "P001",
    name: "MacBook Air M3",
    category: "Electronics",
    seller: "TechZone",
    price: 1299,
    sold: 234,
    revenue: 303966,
    stock: 45,
    rating: 4.8,
    image: null,
  },
  {
    id: "P002",
    name: "Nike Air Max 2024",
    category: "Fashion",
    seller: "FashionHub",
    price: 189,
    sold: 891,
    revenue: 168399,
    stock: 120,
    rating: 4.6,
    image: null,
  },
  {
    id: "P003",
    name: "Samsung 4K QLED TV",
    category: "Electronics",
    seller: "TechZone",
    price: 799,
    sold: 156,
    revenue: 124644,
    stock: 23,
    rating: 4.7,
    image: null,
  },
  {
    id: "P004",
    name: "Yoga Mat Pro",
    category: "Sports",
    seller: "SportsPro",
    price: 65,
    sold: 1230,
    revenue: 79950,
    stock: 300,
    rating: 4.9,
    image: null,
  },
  {
    id: "P005",
    name: "Sofa Set Modern",
    category: "Home & Garden",
    seller: "HomeDecor",
    price: 1499,
    sold: 48,
    revenue: 71952,
    stock: 12,
    rating: 4.5,
    image: null,
  },
];

// ─── Top Sellers ─────────────────────────────────────────────────────────────
export const MOCK_TOP_SELLERS = [
  {
    id: "S001",
    name: "TechZone",
    avatar: null,
    owner: "James Wilson",
    products: 124,
    orders: 2340,
    revenue: 428000,
    rating: 4.8,
    status: "active",
  },
  {
    id: "S002",
    name: "FashionHub",
    avatar: null,
    owner: "Sophie Turner",
    products: 387,
    orders: 4120,
    revenue: 315000,
    rating: 4.6,
    status: "active",
  },
  {
    id: "S003",
    name: "HomeDecor",
    avatar: null,
    owner: "Michael Chen",
    products: 213,
    orders: 1890,
    revenue: 289000,
    rating: 4.7,
    status: "active",
  },
  {
    id: "S004",
    name: "SportsPro",
    avatar: null,
    owner: "Laura Adams",
    products: 156,
    orders: 3210,
    revenue: 198000,
    rating: 4.5,
    status: "active",
  },
  {
    id: "S005",
    name: "BookWorld",
    avatar: null,
    owner: "Paul Brown",
    products: 560,
    orders: 2780,
    revenue: 54000,
    rating: 4.9,
    status: "suspended",
  },
];

// ─── Seller Applications ──────────────────────────────────────────────────────
export const MOCK_SELLER_APPLICATIONS = [
  {
    id: "APP-001",
    businessName: "GadgetPlanet",
    ownerName: "Mark Anderson",
    email: "mark@gadgetplanet.com",
    phone: "+1-555-0101",
    category: "Electronics",
    appliedAt: "2024-12-14",
    status: "pending",
    documents: ["business_reg.pdf", "id_proof.pdf"],
    description: "Specialising in consumer electronics and accessories.",
  },
  {
    id: "APP-002",
    businessName: "StyleCorner",
    ownerName: "Nina Patel",
    email: "nina@stylecorner.com",
    phone: "+1-555-0202",
    category: "Fashion",
    appliedAt: "2024-12-13",
    status: "pending",
    documents: ["business_reg.pdf"],
    description: "Premium fashion and lifestyle brand.",
  },
  {
    id: "APP-003",
    businessName: "OrganicFresh",
    ownerName: "Tom Garcia",
    email: "tom@organicfresh.com",
    phone: "+1-555-0303",
    category: "Food & Grocery",
    appliedAt: "2024-12-12",
    status: "approved",
    documents: ["business_reg.pdf", "health_cert.pdf"],
    description: "Certified organic food products.",
  },
  {
    id: "APP-004",
    businessName: "FitLife",
    ownerName: "Jessica Wong",
    email: "jessica@fitlife.com",
    phone: "+1-555-0404",
    category: "Sports",
    appliedAt: "2024-12-11",
    status: "rejected",
    rejectionReason: "Incomplete documentation provided.",
    documents: ["business_reg.pdf"],
    description: "Sports equipment and fitness gear.",
  },
];

// ─── Recent Activity ─────────────────────────────────────────────────────────
export const MOCK_RECENT_ACTIVITY = [
  {
    id: "ACT-001",
    type: "order",
    message: "New order #ORD-7821 placed by Alice Johnson",
    time: "2 min ago",
    icon: "ShoppingCart",
    color: "blue",
  },
  {
    id: "ACT-002",
    type: "seller",
    message: "Seller application from GadgetPlanet is pending review",
    time: "15 min ago",
    icon: "Store",
    color: "orange",
  },
  {
    id: "ACT-003",
    type: "user",
    message: "New user registered: bob.martinez@email.com",
    time: "1 hr ago",
    icon: "User",
    color: "green",
  },
  {
    id: "ACT-004",
    type: "product",
    message: "Product 'MacBook Air M3' stock is running low (5 left)",
    time: "2 hrs ago",
    icon: "Package",
    color: "red",
  },
  {
    id: "ACT-005",
    type: "order",
    message: "Order #ORD-7817 was cancelled by customer",
    time: "3 hrs ago",
    icon: "ShoppingCart",
    color: "red",
  },
  {
    id: "ACT-006",
    type: "seller",
    message: "TechZone seller account was approved",
    time: "5 hrs ago",
    icon: "Store",
    color: "green",
  },
];

// ─── Users ────────────────────────────────────────────────────────────────────
export const MOCK_USERS = Array.from({ length: 40 }, (_, i) => ({
  id: `USR-${1000 + i}`,
  name: [
    "Alice Johnson", "Bob Martinez", "Carol White", "David Kim",
    "Emma Davis", "Frank Lee", "Grace Hall", "Henry Wilson",
    "Isla Brown", "Jack Taylor", "Karen Moore", "Leo Jackson",
    "Mia Harris", "Noah Martin", "Olivia Thompson", "Peter Garcia",
    "Quinn Martinez", "Rachel Robinson", "Sam Clark", "Tina Lewis",
  ][i % 20],
  email: `user${1000 + i}@example.com`,
  role: i % 8 === 0 ? "SELLER" : "USER",
  status: i % 7 === 0 ? "inactive" : i % 11 === 0 ? "banned" : "active",
  joinedAt: `2024-${String(Math.floor(Math.random() * 12) + 1).padStart(2, "0")}-${String(Math.floor(Math.random() * 28) + 1).padStart(2, "0")}`,
  orders: Math.floor(Math.random() * 50),
  avatar: null,
}));

// ─── Categories ───────────────────────────────────────────────────────────────
export const MOCK_CATEGORIES = [
  { id: "CAT-001", name: "Electronics", slug: "electronics", products: 2340, status: "active", createdAt: "2024-01-10" },
  { id: "CAT-002", name: "Fashion", slug: "fashion", products: 5120, status: "active", createdAt: "2024-01-10" },
  { id: "CAT-003", name: "Home & Garden", slug: "home-garden", products: 1890, status: "active", createdAt: "2024-01-10" },
  { id: "CAT-004", name: "Sports & Outdoors", slug: "sports-outdoors", products: 980, status: "active", createdAt: "2024-02-01" },
  { id: "CAT-005", name: "Books & Media", slug: "books-media", products: 4560, status: "active", createdAt: "2024-02-01" },
  { id: "CAT-006", name: "Food & Grocery", slug: "food-grocery", products: 720, status: "active", createdAt: "2024-03-15" },
  { id: "CAT-007", name: "Toys & Games", slug: "toys-games", products: 1230, status: "active", createdAt: "2024-03-15" },
  { id: "CAT-008", name: "Automotive", slug: "automotive", products: 670, status: "inactive", createdAt: "2024-04-20" },
  { id: "CAT-009", name: "Health & Beauty", slug: "health-beauty", products: 2100, status: "active", createdAt: "2024-04-20" },
  { id: "CAT-010", name: "Pet Supplies", slug: "pet-supplies", products: 430, status: "active", createdAt: "2024-05-05" },
];

// ─── Notifications ────────────────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS = [
  { id: "N001", title: "New seller application", message: "GadgetPlanet submitted a new seller application", time: "2 min ago", read: false, type: "seller" },
  { id: "N002", title: "Large order placed", message: "Order #ORD-7821 worth $2,499 was placed", time: "15 min ago", read: false, type: "order" },
  { id: "N003", title: "Low stock alert", message: "MacBook Air M3 has only 5 units left", time: "1 hr ago", read: false, type: "product" },
  { id: "N004", title: "User banned", message: "User USR-1007 was banned for policy violation", time: "2 hrs ago", read: true, type: "user" },
  { id: "N005", title: "Report generated", message: "Monthly revenue report for November is ready", time: "1 day ago", read: true, type: "report" },
  { id: "N006", title: "System update", message: "Platform maintenance scheduled for Dec 18 at 2AM UTC", time: "2 days ago", read: true, type: "system" },
];
